#+AUTHOR: Bruno Cardoso <cardoso.bc@gmail.com>
#+DATE: 2022-02-01
#+STARTUP: indent content

* org-hop

An interface to hop to Org headings and markers using completing-read.

Alternatively, =helm-org-hop= provides a richer interface to =org-hop=.

** Installation

Clone this repo and add it to your =load-path=:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/org-hop")
(require 'org-hop)
(require 'helm-org-hop) ; optional helm interface
#+end_src

Or, with use-package + straight.el:

#+begin_src emacs-lisp
(use-package org-hop
  :straight (org-hop :host github :repo "bcardoso/org-hop"
                     :files ("org-hop.el"))
  :bind ("C-c h" . org-hop)
  :config
  ;; optional
  (org-hop-recent-mode +1))

;; optional helm interface
(use-package helm-org-hop
  :straight (helm-org-hop :host github :repo "bcardoso/org-hop"
                          :files ("helm-org-hop.el"))
  :bind ("C-c j" . helm-org-hop))
#+end_src


** Usage

Just run =M-x org-hop= or with the suggested binding =C-c h=.

Or, if you are a Helm user, =M-x helm-org-hop= or =C-c j=.

Additionally, you can store markers to any file or buffer with =M-x org-hop-add-marker-to-list= or =M-x org-hop-add-heading-or-marker=.

With the =helm-org-hop= interface, besides hopping, you can store/insert a link to a heading or a marker, and remove them from the recent list.

The =org-hop-recent-mode= keeps track of the headings you spend some time in (see =org-hop-recent-idle-interval=).

The recent headings and markers are shown at the top of the general headings list. To remove them, use =M-x org-hop-remove-heading-from-list= or =M-x org-hop-remove-marker-from-list=.


** Customization

The main customizable variables are accessible through the customize interface:

- =M-x customize-group RET org-hop=
- =M-x customize-group RET helm-org-hop=


By default, =org-hop= will scan all open Org buffers. You can also edit the variables =org-hop-files= and =org-hop-files-extra= to a group of specific files:

#+begin_src emacs-lisp
;; the list of open Org buffers (default)
(setq org-hop-files 'buffers)

;; the list of Org agenda files
(setq org-hop-files 'agenda)

;; the list of Org agenda files + open Org buffers
(setq org-hop-files 'org-files-list)

;; a custom list of Org files
(setq org-hop-files '("x.org" "y.org" "z.org"))

;; the list of Org agenda files + a custom list
;; (the extra files' headings will appear on top)
(setq org-hop-files       'agenda
      org-hop-files-extra '("x.org" "y.org"))
#+end_src

Use the variable =org-hop-files-ignore= to specify a list of Org files that should be ignored.


** Related packages

- =org-goto= (C-c C-j) is a built-in package that allows jumping to a different location in the current file.

- In [[https://github.com/emacs-helm/helm-org/][helm-org]], the =helm-org-agenda-files-headings= and =helm-org-in-buffer-headings= commands allows searching the headings of all Org files or the current buffer, respectively.

  - The main difference of org-hop's approach is that headings are shown with their full-path and file-name appended, making it easier to narrow the search.

- alphapapa's [[https://github.com/alphapapa/org-recent-headings][org-recent-headings]] provides a more sophisticated approach to decide upon recently used Org headings.

  - By contrast, org-hop uses only three simple criteria to consider a heading as "recent" or "visited": 1) you visited a heading through the (helm-)org-hop interface (much like a history); or 2) you spent some time in a heading (with =org-hop-recent-mode=); or 3) you added a heading to the recent list with =M-x org-hop-add-heading-or-marker=.

  - [[https://github.com/alphapapa/org-recent-headings#helm][helm-org-recent-headings]] (and/or other helm sources) can be used within the =helm-org-hop= command:

    #+begin_src emacs-lisp
    (setq helm-org-hop-default-sources '(helm-org-recent-headings-source
                                         helm-source-org-hop-headings))
    #+end_src

- minad's [[https://github.com/minad/consult][consult]] package provides the commands =consult-org-heading= and =consult-org-agenda= for narrowing and jumping to Org headings.


